apiVersion: v1
kind: Service
metadata:
  name: governify-director
  namespace: governify-next
spec:
  selector:
    app: governify-director
  ports:
    - protocol: TCP
      port: 5806
      targetPort: 5806