apiVersion: v1
kind: Service
metadata:
  name: governify-registry
  namespace: governify-next
spec:
  selector:
    app: governify-registry
  ports:
    - protocol: TCP
      port: 5802
      targetPort: 5802