apiVersion: v1
kind: Secret
metadata:
  name: governify-secrets
  namespace: governify-next
type: Opaque
stringData:
  jwt_secret: REPLACE_WITH_AT_LEAST_32_RANDOM_BYTES
  influx_token: apiv3_REPLACE_WITH_AT_LEAST_16_RANDOM_BYTES
  influx_admin_token.json: |
    {
      "token": "apiv3_REPLACE_WITH_THE_SAME_TOKEN",
      "name": "governify-admin"
    }
  grafana_user: governify-admin
  grafana_password: REPLACE_WITH_A_RANDOM_PASSWORD
  oidc_client_id: REPLACE_WITH_OIDC_CLIENT_ID
  oidc_client_secret: REPLACE_WITH_OIDC_CLIENT_SECRET
