apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo.yaml
  - redis.yaml
  - influxdb.yaml
  - grafana.yaml
  - headlamp.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
