apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: governify-influxdb3
  name: governify-influxdb3
  namespace: governify-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governify-influxdb3
  template:
    metadata:
      labels:
        app: governify-influxdb3
    spec:
      containers:
        - name: governify-influxdb3
          image: influxdb:3-core
          imagePullPolicy: Always
          args:
            - serve
            - --node-id=reporter-node
            - --object-store=file
            - --data-dir=/var/lib/influxdb3
          ports:
            - containerPort: 8181
              protocol: TCP
          volumeMounts:
            - name: influxdb3-data
              mountPath: /var/lib/influxdb3
      volumes:
        - name: influxdb3-data
          persistentVolumeClaim:
            claimName: governify-influxdb3
