kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: governify-influxdb3
  namespace: governify-next
  labels:
    app: governify-influxdb3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
