kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: governify-grafana
  namespace: governify-next
  labels:
    app: governify-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
