apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: governify-computer
  name: governify-computer
  namespace: governify-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: governify-computer
  template:
    metadata:
      labels:
        app: governify-computer
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: GOV_LOG_LEVEL
              value: INFO
            - name: PORT
              value: "5803"
            - name: GOV_SERVICE_NAME
              value: "computer"
            - name: MONGO_URI
              value: "mongodb://governify-mongo:27017/governify"
            - name: REDIS_URI
              value: "redis://governify-redis:6379"
            - name: COLLECTOR_SERVICE_URL
              value: "http://governify-collector:5804"
            - name: SERVICE_AUTHENTICATION_ENABLED
              value: "false"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: governify-secrets
                  key: jwt_secret
            - name: REDIS_ENABLED
              value: "false"
            - name: REDIS_MAX_RETRIES
              value: "5"
            - name: REDIS_RETRY_DELAY_MS
              value: "2000"
            - name: REDIS_SLOW_RECONNECTION_MAX_RETRIES
              value: "10"
            - name: REDIS_SLOW_RECONNECTION_STRATEGY
              value: "false"
            - name: REDIS_RETRY_SLOW_DELAY_MS
              value: "10000"
            - name: FETCH_RESULT_POLLING_MAX_ATTEMPTS
              value: "300"
            - name: FETCH_RESULT_POLLING_INTERVAL_MS
              value: "1000"
          image: governifynext/computer:develop
          imagePullPolicy: Always
          name: governify-computer
          ports:
            - containerPort: 5803
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 400Mi