apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: governify-computer
  namespace: governify-next
  labels:
    app: governify-computer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: governify-computer
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75