apiVersion: v1
kind: Service
metadata:
  name: governify-reporter
  namespace: governify-next
spec:
  selector:
    app: governify-reporter
  ports:
    - protocol: TCP
      port: 5805
      targetPort: 5805