apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: governify-next
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  commonUpdateSettings:
    updateStrategy: digest
  applicationRefs:
    - namePattern: governify-next
      images:
        - alias: authenticator
          imageName: governifynext/authenticator:develop
        - alias: fetcher
          imageName: governifynext/fetcher:develop
        - alias: computer
          imageName: governifynext/computer:develop
        - alias: director
          imageName: governifynext/director:develop
        - alias: registry
          imageName: governifynext/registry:develop
        - alias: reporter
          imageName: governifynext/reporter:develop
        - alias: scopemanager
          imageName: governifynext/scope-manager:develop
        - alias: joinbackend
          imageName: governifynext/join-backend:develop
        - alias: joinfrontend
          imageName: governifynext/join-frontend:develop
