apiVersion: v1
kind: Service
metadata:
  name: governify-scope-manager
  namespace: governify-next
spec:
  selector:
    app: governify-scope-manager
  ports:
    - protocol: TCP
      port: 5801
      targetPort: 5801