apiVersion: apps/v1
kind: Deployment
metadata:
  name: governify-fetcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: governify-fetcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: governify-fetcher
    spec:
      containers:
        - name: fetcher
          image: governifynext/fetcher:develop
          env:
            - {name: SERVICE_AUTHENTICATION_ENABLED, value: "true"}
            - {name: NODE_ENV, value: production}
            - {name: GOV_LOG_LEVEL, value: INFO}
            - {name: AUTHENTICATOR_SERVICE_URL, value: "http://governify-authenticator:5800"}
            - {name: CLIENT_ID, value: fetcher}
            - name: CLIENT_SECRET
              valueFrom: {secretKeyRef: {name: governify-secrets, key: fetcher_client_secret}}
            - {name: PORT, value: "5804"}
            - {name: GOV_SERVICE_NAME, value: fetcher}
            - {name: MONGO_URI, value: "mongodb://governify-mongo:27017/governify"}
            - name: JWT_SECRET
              valueFrom: {secretKeyRef: {name: governify-secrets, key: jwt_secret}}
            - {name: JWT_ISSUER, value: authenticator}
            - {name: JWT_AUDIENCE, value: governify-next}
            - name: GITHUB_APP_ID
              valueFrom: {secretKeyRef: {name: governify-secrets, key: github_app_id}}
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom: {secretKeyRef: {name: governify-secrets, key: github_app_private_key}}
---
apiVersion: v1
kind: Service
metadata:
  name: governify-fetcher
spec:
  selector:
    app.kubernetes.io/name: governify-fetcher
  ports:
    - {port: 5804}
