apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: governify-next
spec:
  tls:
    - hosts:
        - scope-manager.k8s.next.governify.io
        - registry.k8s.next.governify.io
        - computer.k8s.next.governify.io
        - collector.k8s.next.governify.io
        - reporter.k8s.next.governify.io
        - director.k8s.next.governify.io
        - grafana.k8s.next.governify.io
  rules:
    - host: scope-manager.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-scope-manager
                port:
                  number: 5801
    - host: registry.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-registry
                port:
                  number: 5802
    - host: computer.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-computer
                port:
                  number: 5803
    - host: collector.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-collector
                port:
                  number: 5804
    - host: reporter.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-reporter
                port:
                  number: 5805
    - host: director.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-director
                port:
                  number: 5806
    - host: grafana.k8s.next.governify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: governify-grafana
                port:
                  number: 3000
