apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: governify-next
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`scope-manager.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-scope-manager, port: 5801}]
    - match: Host(`registry.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-registry, port: 5802}]
    - match: Host(`computer.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-computer, port: 5803}]
    - match: Host(`collector.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-collector, port: 5804}]
    - match: Host(`reporter.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-reporter, port: 5805}]
    - match: Host(`director.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-director, port: 5806}]
    - match: Host(`grafana.k8s.next.governify.io`)
      kind: Rule
      services: [{name: governify-grafana, port: 3000}]
  tls:
    certResolver: default
