apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governify-next
resources:
  - core.yaml
  - infra
  - services/authenticator.yaml
  - services/fetcher.yaml
  - services/computer.yaml
  - services/director.yaml
  - services/registry.yaml
  - services/reporter.yaml
  - services/scope-manager.yaml
  - services/join-backend.yaml
  - services/join-frontend.yaml
  - ingress.yaml
