apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governify-next
resources:
  - core.yaml
  - apps/collector.yaml
  - apps/computer.yaml
  - apps/director.yaml
  - apps/registry.yaml
  - apps/reporter.yaml
  - apps/scope-manager.yaml
  - data/mongo.yaml
  - data/redis.yaml
  - data/influxdb.yaml
  - data/grafana.yaml
  - ingress.yaml
