apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governify-next
resources:
  - core.yaml
  - services/collector.yaml
  - services/computer.yaml
  - services/director.yaml
  - services/registry.yaml
  - services/reporter.yaml
  - services/scope-manager.yaml
  - infra/mongo.yaml
  - infra/redis.yaml
  - infra/influxdb.yaml
  - infra/grafana.yaml
  - infra/headlamp.yaml
  - ingress.yaml
