apiVersion: v1
kind: Service
metadata:
  name: governify-collector
  namespace: governify-next
spec:
  selector:
    app: governify-collector
  ports:
    - protocol: TCP
      port: 5804
      targetPort: 5804