apiVersion: v1
kind: Service
metadata:
  name: governify-mongo
  namespace: governify-next
spec:
  selector:
    app: governify-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017